### ISSUE TITLE
Chord names are not standard across pages

### ISSUE THREAD

**Issue by oakleyaidan21** [saxocellphone/MagicVoicing#2]
Chord names across different songs can vary.

i.e., on one page an E flat major seventh would be listed as `Eb7`, and on another page it will be `Eb^7`

**Comment by saxocellphone** [comment]
I think in this case the Eb7 means that the 7 is dominant, and the 7 in Eb^7 means the 7 is major

**Comment by oakleyaidan21** [comment]
Yup, you're right! Thought they were the same, oops.
